const { chromium } = require('playwright-core');
(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/meta-chromium/chrome',
    args: ['--no-sandbox','--disable-dev-shm-usage','--proxy-server=http://127.0.0.1:9999'] });
  const ctx = await browser.newContext({ userAgent: 'curl/8.5.0', viewport: { width: 1280, height: 800 } });
  const page = await ctx.newPage();
  const errs = [];
  page.on('pageerror', e => errs.push(e.message.slice(0,100)));
  await page.goto('https://tintajunta-sala.loca.lt/', { waitUntil: 'domcontentloaded', timeout: 60000 });
  await page.waitForSelector('#nameInput', { timeout: 30000 });
  await page.fill('#nameInput', 'KingFinal');
  await page.click('#joinBtn');
  await page.waitForSelector('.w', { timeout: 30000 });
  await page.waitForFunction(() => typeof netOnline !== 'undefined' && netOnline === true, null, { timeout: 30000 });
  await page.waitForTimeout(2000);
  console.log('1) conectado, lápiz:', await page.evaluate(() => document.getElementById('pencilBtn').classList.contains('on')));
  await page.locator('.w').nth(60).scrollIntoViewIfNeeded();
  await page.waitForTimeout(800);
  const a = await page.locator('.w').nth(60).boundingBox();
  const b = await page.locator('.w').nth(72).boundingBox();
  await page.mouse.move(a.x + a.width/2, a.y + a.height/2);
  await page.mouse.down();
  await page.mouse.move(b.x + b.width/2, b.y + b.height/2, { steps: 20 });
  await page.mouse.up();
  await page.waitForTimeout(2500);
  const painted = await page.evaluate(() => [...document.querySelectorAll('.w')].filter(s => s.style.background).length);
  const st = await page.evaluate(() => fetch('/api/state').then(r => r.json()));
  const mine = st.highlights.filter(h => h.name === 'KingFinal');
  console.log('2) pintadas:', painted, '| guardados:', mine.length, mine.length ? `rango ${mine[0].start}-${mine[0].end}` : '');
  console.log('3) barra oculta:', await page.evaluate(() => document.getElementById('toolbar').classList.contains('hidden')));
  console.log('errores JS:', errs.length ? errs : 'ninguno');
  await browser.close();
})();
